from django.core.management.base import BaseCommand
from readings.models import Card

class Command(BaseCommand):
    help = 'Bulk create Card objects from a list'

    def handle(self, *args, **options):
        cards_list = [
            {"name": "Kvailys", "image": "00.png",
                "meaning": "Nauja pradžia, spontaniškumas, tikėjimo šuolis, nekaltumas.",
                "r_meaning": "Kvailystė, neapdairumas, blogas sprendimas, chaosas.",
                "description": "Kvailys reiškia naujos kelionės, kupinos galimybių ir optimistiškos perspektyvos, pradžią. Šios kortos gavimas taip pat primena neskubėti pirmyn, suvokti tai, ko nežinai, ir eiti savirealizacijos keliu.",
                "arcana": "major", "suit": "none",
                "id": 0},
            {"name": "Magas", "image": "01.png",
                "meaning": "Galia, įgūdžiai, pasireiškimas, koncentracija, valios jėga, psichinės galios.",
                "r_meaning": "Blogas planavimas, manipuliavimas, godumas, nepatiklumas.",
                "description": "Magas simbolizuoja talentą, pasiaukojimą, paslaptį ir žinias. Tai taip pat gali rodyti blogą sveikatą ir praradimą metaforine prasme; tai gebėjimų ar orumo praradimas, atsirandantis dėl neteisingos krypties.",
                "arcana": "major", "suit": "none",
                "id": 1},
            {"name": "Žynė", "image": "02.png",
                "meaning": "Tiesa, intuicija, pasąmonė, aukštesnė jėga.",
                "r_meaning": "Užslopinti jausmai, nusivylimas, psichiniai blokai, paslapčių laikymas.",
                "description": "Skaitant Taro kortas, žynė turi didelę reikšmę mūsų intuicijai ir pasitikėjimui savo nuojautai. Šios dvasinės dieviškosios kortos gavimas simbolizuoja poreikį pasitikėti savo intuicija.",
                "arcana": "major", "suit": "none",
                "id": 2},
            {"name": "Imperatorienė", "image": "03.png",
                "meaning": "Dieviškasis moteriškumas, motinystė, kūrybiškumas, nėštumas, moterišku",
                "r_meaning": "Nesaugumas, sunkumai pastoti, augimo trūkumas, valdingumas.",
                "description": "Imperatorienė turi galingą žinią, skirtą dieviškajai moteriškajai energijai. Kvietimas į moterystę ir motinystę, šios kortelės gavimas simbolizuoja poreikį atsiduoti savo puoselėjamai pusei ir namų gyvenimui, taip pat žengti nauju dvasingumo keliu.",
                "arcana": "major", "suit": "none",
                "id": 3},
            {"name": "Imperatorius", "image": "04.png",
                "meaning": "Stabilumas, kontrolė, disciplina, tėvo figūra.",
                "r_meaning": "Užsispyręs, neapgalvotas, nekontroliuojamas, nelankstumas.",
                "description": "Imperatorius yra lyderystės ir noro pritraukti stiprų draugą simbolis . Šis vadovas taip pat yra išminties simbolis, pasiekiamas tik per gyvenimišką patirtį.",
                "arcana": "major", "suit": "none",
                "id": 4},
            {"name": "Šventikas", "image": "05.png",
                "meaning": "Tradicinės vertybės, religija, įsipareigojimas, atitiktis.",
                "r_meaning": "Laisvė, sudėtingos tradicijos, vaidmenų apsikeitimas.",
                "description": "Šventikas reiškia tradiciją, seną veiklos būdą ir susiliejimą su didele institucija siekiant savo tikslų. Jo tikslas – nukreipti jus teisinga linkme, kad su jo vedimu atrastumėte savo tiesą.",
                "arcana": "major", "suit": "none",
                "id": 5},
            {"name": "Įsimylėjeliai", "image": "06.png",
                "meaning": "Harmonija, meilė, papildoma energija, trauka.",
                "r_meaning": "Disbalansas, įsipareigojimo baimė, šaltumas, nesėkmė.",
                "description": "Ištraukę šią kortą reiškia, kad turite priimti sprendimą ir pasirinkti iš dviejų kelių. Šioje kryžkelėje ši korta skatina rasti pusiausvyrą savyje, nepaisant netikrumo su tais, kurie gyvena jūsų gyvenime.",
                "arcana": "major", "suit": "none",
                "id": 6},
            {"name": "Vežimas", "image": "07.png",
                "meaning": "Sėkmė, atkaklumas, jėga, ambicijos, kliūčių įveikimas.",
                "r_meaning": "Krypties trūkumas, valios stoka, nekontroliavimas savęs.",
                "description": "Vežimas reiškia poreikį veržtis į priekį ir būti nepajudinamiems, taip pat įveikti iššūkius. Tai gali reikšti, kad mūsų laukia geri dalykai, tačiau tai taip pat primena, kad turime dirbti, kad gautume naudos.",
                "arcana": "major", "suit": "none",
                "id": 7},
            {"name": "Jėga", "image": "08.png",
                "meaning": "Gera sveikata, vidinė jėga, drąsa, drąsa, užuojauta.",
                "r_meaning": "Silpnumas, nepasitikėjimas savimi, pažeidžiamumas, nesaugumas.",
                "description": "Šios kortos reikšmė yra tiesmuka. Reiškia drąsą ir artėjančią pergalę. Ši korta pasirodo tada, kai mums reikia priminimo, kad stumtume pirmyn, ir kad mums pasiseks, jei į ką nors įdėsime visas jėgas.",
                "arcana": "major", "suit": "none",
                "id": 8},
            {"name": "Atsiskyrėlis", "image": "09.png",
                "meaning": "Savistaba, žvilgsnis į vidų, vidinis vadovavimas, dvasinis nušvitimas.",
                "r_meaning": "Izoliacija, vienatvė, atsiribojimas.",
                "description": "Kai būrimo metu gaunate šią kortą, tai reiškia, kad turite užmegzti ryšį su savimi, žengti žingsnį atgal, kad pasiruoštumėte išminties ir jėgos reikalaujančiai užduočiai. Reikia atsitraukti ir rasti dvasinį atsinaujinimą, patirti katarsį.",
                "arcana": "major", "suit": "none",
                "id": 9},
            {"name": "Laimės Ratas", "image": "10.png",
                "meaning": "Sėkmės, sielos draugai, gera karma, teigiama rizika.",
                "r_meaning": "Nesėkmės, nesusipratimai, vėlavimas, trukdžiai, vėlavimai.",
                "description": "Korta „Laimės ratas“ simbolizuoja ateinančią galimybę. Tačiau viskas priklauso nuo to, ką pasirinksite daryti su galimybe, kuri nulems rezultatą.",
                "id": 10},
            {"name": "Teisingumas", "image": "11.png",
                "meaning": "Teisingumas, teisė, karminis teisingumas, tiesa, sąžiningumas.",
                "r_meaning": "Nesąžiningumas, netinkamas elgesys, disbalansas.",
                "description": "Sąžiningumo ir pusiausvyros simbolis, teisingumo korta pasirodo kaip priminimas pasitikėti savo intuicija, kaip ir žynės korta. Ši korta reiškia poreikį priimti sprendimus naudojant logiką ir šaltą protą.",
                "arcana": "major", "suit": "none",
                "id": 11},
            {"name": "Pakabintasis", "image": "12.png",
                "meaning": "Netikrumas, pasidavimas, krypties nebuvimas.",
                "r_meaning": "Neryžtingumas, sąstingis, apatija, pasipriešinimas, atsiribojimas.",
                "description": "Pakabintas žmogus simbolizuoja kito laukimą ir nekantrumą. Tai atsiranda, kai reikia žengti žingsnį atgal ir suvokti, ką turi savo gyvenime, savo pasirinkimų pasekmes ir susitaikyti su savo situacijomis nesitikint kažko kito.",
                "id": 12},
            {"name": "Mirtis", "image": "13.png",
                "meaning": "Nauja pradžia, perėjimai, netikėti pokyčiai, dvasinis virsmas.",
                "r_meaning": "Nesugebėjimas judėti į priekį, pasipriešinimas pokyčiams, baimė, nesveiki modeliai.",
                "description": "Nors galite manyti, kad mirties korta yra blogas ženklas, ji iš tikrųjų simbolizuoja naujos pradžios pradžią ; vienas skyrius baigiasi, todėl gali prasidėti kitas. Tai galimybė pasitikti nauja energija ar aplinkybėmis, pašalinant viską, kas mums nebetarnauja.",
                "arcana": "major", "suit": "none",
                "id": 13},
            {"name": "Saikingumas", "image": "14.png",
                "meaning": "Pusiausvyra, vidinė ramybė, sielos draugų ryšiai.",
                "r_meaning": "Disbalansas, chaosas, uždarumas, nesirūpinimas.",
                "description": "Nors tai simbolizuoja mąstymą ir nerimą , tai taip pat sveikintinas ženklas ir reiškia gyvenimo pusiausvyrą po iššūkių. Gauti šią kortą reiškia kiekvieną dieną daryti viską, ką gali, dėl tikros ramybės.",
                "arcana": "major", "suit": "none",
                "id": 14},
            {"name": "Velnias", "image": "15.png",
                "meaning": "Nesąžiningumas, prievarta, amorali veikla, psichikos sveikatos problemos.",
                "r_meaning": "Nepriklausomybė, laisvė, įžvalga.",
                "description": "Velnias pasirodo tada, kai įkimstate į blogus įpročius ir pasikliaujate savo ydomis. Tai įspėjimas, kad reikia pavargti nuo sudėtingų situacijų, nes viskas nėra taip, kaip atrodo.",
                "arcana": "major", "suit": "none",
                "id": 15},
            {"name": "Bokštas", "image": "16.png",
                "meaning": "Chaosas, nelaimė, transformacija, netikėti pokyčiai.",
                "r_meaning": "Pokyčių vengimas, neišvengiamų situacijų vilkinimas.",
                "description": "Staigios bėdos korta – Bokštas reiškia, kad artėja pokyčiai, kurių neįmanoma išvengti, kad ir kaip tai būtų nemalonu. Tai taip pat simbolizuoja išaiškėjusią tiesą, taip pat pasiekimą taško, iš kurio nėra sugrįžimo.",
                "arcana": "major", "suit": "none",
                "id": 16},
            {"name": "Žvaigždė", "image": "17.png",
                "meaning": "Viltis, tikėjimas, kūrybiškumas, dvasingumas, įkvėpimas.",
                "r_meaning": "Atsijungimas, neviltis, kūrybiškumo stoka/įkvėpimo.",
                "description": "Žvaigždės kortos gavimas būrimo metu reiškia, kad turėtumėte atkreipti dėmesį į savo dvasingumą, nes jums suteikiamos galimybės ir palaiminimai. Tai taip pat siejama su angelais ir teigiamais ženklais.",
                "arcana": "major", "suit": "none",
                "id": 17},
            {"name": "Mėnulis", "image": "18.png",
                "meaning": "Netikrumas, iliuzija, sumišimas, paslaptys, nestabilumas, baimė.",
                "r_meaning": "Užgniaužtos emocijos, nurimęs nerimas, tiesa, santūrumas, aiškumas.",
                "description": "Mėnulis reiškia galimybę pabandyti dar kartą, susitaikyti su likimu arba pakeisti save į gerąją pusę. Tai rodiklis, kad gyvenime reikia pusiausvyros, jei nori, kad tau atsirastų geri dalykai.",
                "id": 18},
            {"name": "Saulė", "image": "19.png",
                "meaning": "Pasitikėjimas, sėkmė, tiesa, sėkmė, pozityvumas.",
                "r_meaning": "Abejingumas, pesimizmas, pasipūtimas.",
                "description": "Kaip metaforinis ir tiesioginis šviesos šaltinis, Saulės korta reiškia gerus laikus, net ir nelaimių metu. Sėkmė laukia ateityje, kaip ir įspėjimas nustoti vargti.",
                "arcana": "major", "suit": "none",
                "id": 19},
            {"name": "Teismas", "image": "20.png",
                "meaning": "Savęs pažinimas, atleidimas, nauja pradžia, užsidarymas.",
                "r_meaning": "Neryžtingumas, neapykanta sau, nežinojimas, kitų kaltinimas.",
                "description": "Kai gausite Teismo kortą, žinokite, kad ji simbolizuoja poreikį galvoti apie save, duoda mums postūmį priimti geresnius sprendimus ir išsivaduoti iš vidinių neramumų.",
                "arcana": "major", "suit": "none",
                "id": 20},
            {"name": "Pasaulis", "image": "21.png",
                "meaning": "Pasiekimai, pozityvumas, kūryba, išsipildymas.",
                "r_meaning": "Nesėkmė, praradimas, sąstingis, tinginystė.",
                "description": "Paskutinė Didžiųjų Arkanų korta Pasaulis – reiškia gyvenimo ratą ir naujo laikotarpio pradžią. Jūsų įdėtos pastangos baigiasi ir veda į pabaigą bei pasiekimus.",
                "arcana": "major", "suit": "none",
                "id": 21},
            {"name": "Lazdų tūzas", "image": "Wands01.png",
                "meaning": "Naujų projektų kūrimas, nauja draugystė, nauja pradžia.",
                "r_meaning": "Nesėkmė, praradimas, sąstingis, tinginystė.",
                "description": "Kaip kūrybingos energijos simbolis, ši korta išreiškia įkvėpimą ir gerą bendravimą bei teikia pirmenybę visiems naujiems planams ir projektams.",
                "arcana": "minor", "suit": "wands",
                "id": 22},
            {"name": "Lazdų dvejetas", "image": "Wands02.png",
                "meaning": "Pelningas pasiūlymas, sutaps mąstymas, poreikiai.",
                "r_meaning": "Susidūrimas su priešingybėmis, interesų nebuvimas.",
                "description": "Suteikiama pagalba ir daroma pažanga partnerystėse. Yra lygybė ir finansinis saugumas, ir jūs kartu puikiai tvarkote savo verslą, naują projektą ar buitinę tvarką.",
                "arcana": "minor", "suit": "wands",
                "id": 23},
            {"name": "Lazdų trejetas", "image": "Wands03.png",
                "meaning": "Naujų projektų kūrimas, nauja draugystė, nauja pradžia.",
                "r_meaning": "Išdidumas, arogancija ir nenoras įvertinti situacijos objektyviai.",
                "description": "Atskleidžia kūrybiškumą ir saviraišką bei projektų vystymą. Įvykiai paspartėja, nes atsiranda daugiau bendravimo, veiksmų ir atlygio.",
                "arcana": "minor", "suit": "wands",
                "id": 24},
            {"name": "Lazdų ketvertas", "image": "Wands04.png",
                "meaning": "Derliaus korta, darbų užbaigimas, pasiekimai, sėkmė namuose.",
                "r_meaning": "Apribojimai ir beprasmiškumo pojūtis. Nedėkingumas ir nusivylimas. Neišsipildžiusios viltys vers gailėtis.",
                "description": "Jūs sujungiate įvairius savo gyvenimo elementus ir suteikiate didesnį malonumą darbui, namams, draugams ir šeimai. Tikėtina, kad nauja nuosavybė arba esamo namo tobulinimo darbai išsiplėtę į didesnę ar tinkamesnę erdvę.",
                "arcana": "minor", "suit": "wands",
                "id": 25},
            {"name": "Lazdų penketas", "image": "Wands05.png",
                "meaning": "Darbštumas, išbandymas, iššūkis, varžybos, įrodyti savo jėgas ir sugebėjimus.",
                "r_meaning": "Apgaulė, barniai ir nesusipratimai. Reikaluose kylančios problemos.",
                "description": "Penkios lazdos rodo, kad jums teks susidurti su aštrios konkurencijos sąlygomis. Teks įrodinėti asmenines pozicijas ir tai bus susiję su didelėmis išlaidomis. Versle ši korta rodo didelę konkurenciją.",
                "arcana": "minor", "suit": "wands",
                "id": 26},
            {"name": "Lazdų šešetas", "image": "Wands06.png",
                "meaning": "Didžiuotis, pasiteisins ambicijos, sėkmė laukia bet kuriame kelyje.",
                "r_meaning": "Neramumas, sėkmė vėluos, jaudulys ir baimė dėl ateities.",
                "description": "Po sunkaus darbo ateina proveržis su fantastiška žinia apie ilgai lauktą apdovanojimą ar ginčo pabaigą.",
                "arcana": "minor", "suit": "wands",
                "id": 27},
            {"name": "Lazdų septynetas", "image": "Wands07.png",
                "meaning": "Pozicijų neužleidimas, užsispyrimas, atkaklumas. Sėkmė per kančias.",
                "r_meaning": "Drovumas, abejonės savimi ir neapsisprendimas.",
                "description": "Laukia nelengvas kelias, bet atkaklumo dėka pasieksite savo tikslą. Tai sudėtinga, nes gali praeiti šiek tiek laiko, kol pamatysite grąžą už sunkų darbą.",
                "arcana": "minor", "suit": "wands",
                "id": 28},
            {"name": "Lazdų aštuonetas", "image": "Wands08.png",
                "meaning": "Delsimas, netikėtos problemos planuose.",
                "r_meaning": "Kelionės, judėjimas ir greiti sprendimai jau jūsų rankose.",
                "description": "Yra puikių naujienų apie kelionę ar projektą, jūsų laukia labai įtemptas metas – siūloma daug idėjų, veiklos ir pasiūlymų. ",
                "arcana": "minor", "suit": "wands",
                "id": 29},
            {"name": "Lazdų devynetas", "image": "Wands09.png",
                "meaning": "Atsparumas, išradingumas, pasitikėjimas savimi, stabilumas ir jėga.",
                "r_meaning": "Užsispyrimas, nenoras ieškoti kompromisų, nepalenkiama valia.",
                "description": "Spaudimo patyrimas netinkamu metu, Energijos atradimas – protinio aktyvumo, palaikančių žmonių ir pakankamai veržlumo – išgyventi šį stimuliuojantį, nors ir įtemptą laikotarpį.",
                "id": 30},
            {"name": "Lazdų dešimtis", "image": "Wands10.png",
                "meaning": "Našta, sunkios pareigos, stresas ir begalės darbų.",
                "r_meaning": "Nesėkmė, praradimas, sąstingis, tinginystė.",
                "description": "Sudėtingą užduotį teks užbaigti ir galų gale jums pasiseks. Gali pakrikti tiek nervai, tiek sveikata, tačiau užbaigsite viską. Pasidairykite, gal dalį naštos yra kam perkelti.",
                "arcana": "minor", "suit": "wands",
                "id": 31},
            {"name": "Lazdų Valetas", "image": "Wands11.png",
                "meaning": "Atsargi pažanga, keliautojas, puikiai prisitaikantis, nuoširdžiai dirbantis.",
                "r_meaning": "Nuolatos besiskundžiantis asmuo, manipuliavimas.",
                "description": "Geros naujienos ir prognozės, kad jūsų dėmesį patrauks keli svarbūs dalykai. Reiktų nepamiršti patikrinti faktus, o ne tikėti viskuo, ką girdite.",
                "arcana": "minor", "suit": "wands",
                "id": 32},
            {"name": "Lazdų Riteris", "image": "Wands12.png",
                "meaning": "Tvirtumas, kūrybiškumas, sėkmė.",
                "r_meaning": "Pavydas, agresyvumas, nenuoširdumas.",
                "description": "Viskas, ko laukėte, pradeda materializuotis, įkvepiantis verslumo etapas.",
                "id": 33},
            {"name": "Lazdų Dama", "image": "Wands13.png",
                "meaning": "Įkvėpimas, aistra, gyvybingumas.",
                "r_meaning": "Nepatikimumas, kerštingumas, diktatūra.",
                "description": "Kaip kūrybingos energijos simbolis, ši korta išreiškia įkvėpimą ir gerą bendravimą bei teikia pirmenybę visiems naujiems planams ir projektams.",
                "arcana": "minor", "suit": "wands",
                "id": 34},
            {"name": "Lazdų Karalius", "image": "Wands14.png",
                "meaning": "Garbė, užuojauta, gerumas ir dosnumas.",
                "r_meaning": "Netolerancija, nepakantumas, žiaurumas ir agresyvumas.",
                "description": "Ši korta reiškia ramybę, sąžiningumą ir užuojautą. Korta atskleidžia garbingą elgesį, taip pat gali parodyti, kad dabar jausitės pilnavertiškai.",
                "arcana": "minor", "suit": "wands",
                "id": 35},
            {"name": "Taurių tūzas", "image": "Cups01.png",
                "meaning": "Meilė, nauji santykiai, užuojauta, kūrybingumas",
                "r_meaning": "Savimeilė, intuicija, užslėptos emocijos",
                "description": "Dabar svarbu ieškoti naujų draugų, meilės, tobulėti dvasiškai. Metas užmiršti praeities negandas. Metas gyventi šia akimirka ir mėgautis.",
                "arcana": "minor", "suit": "cups",
                "id": 36},
            {"name": "Taurių dvejetas", "image": "Cups02.png",
                "meaning": "Meilė, aistra, draugystė, sąjunga, giminystė, santarvė – sutarimas, simpatija.",
                "r_meaning": "Ginčai dėl smulkmenų, savanaudiškumas, nesantaika, uždarumas.",
                "description": "Viena svarbi dalis, susijusi su dviem taurėmis – tai partnerystė. Kokia partnerystė – nėra taip paprastai aišku. Tai gali būti ypač emocinis meilės reikalas, tačiau, taip pat, gali būti gili ir tvirta draugystė.",
                "arcana": "minor", "suit": "cups",
                "id": 37},
            {"name": "Taurių trejetas", "image": "Cups03.png",
                "meaning": "Idealizmas, linksmumas, laimingas rezultatas, pilnavertiškumas, paguoda.",
                "r_meaning": "Nutolimas nuo draugų, harmonijos trūkumas, apkalbos, skandalai, pavydas.",
                "description": "Ši korta reiškia šventę, susitikimą su draugais, gerą laiko praleidimą. Tai gali būti sėkmingas suplanuoto projekto, remonto, arba veiklos užbaigimas. Taip pat, tai gali reikšti ir sėkmingą gimdymą, naujos būtybės atėjimą.",
                "arcana": "minor", "suit": "cups",
                "id": 38},
            {"name": "Taurių ketvertas", "image": "Cups04.png",
                "meaning": "Nuovargis, bjaurėjimasis, apatija, sąstingis, abejotini patarimai.",
                "r_meaning": "Naujovės, pranašystė, naujo etapo padžia, ambicijos.",
                "description": "Keturios taurės reiškia apatiją ir melancholiją. Tai pavojingas laikotarpis, kai tikėdamiesi, kad viską turite ir nesirūpindami tuo, galite viską prarasti.",
                "arcana": "minor", "suit": "cups",
                "id": 39},
            {"name": "Taurių penketas", "image": "Cups05.png",
                "meaning": "Nusivylimas, sielvartas, prarastos galimybės, nesimokymas iš praeities klaidų.",
                "r_meaning": "Laiko užgydytos žaizdos, išmoktos pamokos, stiprybė, nusiraminimas.",
                "description": "Emociniai ryšiai su aplinka. Jeigu jums trūksta pozityvumo ir optimizmo – jausite nusivylimą ir apgailestavimą. Taip pat ši korta reiškia giminystės santykius, įsipareigojimus artimiems giminaičiams.",
                "arcana": "minor", "suit": "cups",
                "id": 40},
            {"name": "Taurių šešetas", "image": "Cups06.png",
                "meaning": "Sentimentalumas, vidinis vaikas, žaismingumas, dalijimasis ir susitaikymas.",
                "r_meaning": "Gyvenimas praeitimi, atsinaujinimas, atlaidumas sau.",
                "description": "Veiksmai, padaryti praeityje, kad šiandien būtumėte laimingi. Emocinis ryšys su artimais žmonėmis, pastangos išlaikyti šeimos tvirtumą ir gerovę. Taip pat, ši korta reiškia emocinį meilės ryšį tarp partnerių šeimoje.",
                "arcana": "minor", "suit": "cups",
                "id": 41},
            {"name": "Taurių septynetas", "image": "Cups07.png",
                "meaning": "Nuolaidžiavimas sau, nerealistiški lūkesčiai, vaizduotė, tingumas, iliuzijos.",
                "r_meaning": "Troškimas, valia, ryžtingumas, projektavimas, pasiekimas - iškritus laimingoms kortoms.",
                "description": "Ši korta neturi nieko bendro su realybe. Tai jūsų svajonės, lūkesčiai ir planai. Kad jie išsipildytų, reikia kitų gerų kortų paramos ir pagalbos. Iškritus blogoms kortoms – gręsia nutolimas nuo realybės, klystkeliai, iliuzijos.",
                "arcana": "minor", "suit": "cups",
                "id": 42},
            {"name": "Taurių aštuonetas", "image": "Cups08.png",
                "meaning": "Pokyčiai, judėjimas į priekį, tyrinėjimas, nepalankios situacijos palikimas.",
                "r_meaning": "Puotavimas, šventė, plaukimas pasroviui, komforto zona, neapsisprendimas.",
                "description": "Gyvenimo ir laimės paieškos. Nors esate stabilus žmogus, bet vis dar ieškote laimės. jeigu turėsite pakankamai drąsos – jūsų gyvenimas atsinaujins ir rasite savo asmeninę vertę.",
                "arcana": "minor", "suit": "cups",
                "id": 43},
            {"name": "Taurių devynetas", "image": "Cups09.png",
                "meaning": "Santarvė, pasitenkinimas, fiziškas-materialus gerbūvis, atsakas į maldas.",
                "r_meaning": "Arogancija, snobizmas, pilnatviškumo trūkumas, nuolaidžiavimas sau.",
                "description": "Pasitenkinimas gyvenimu, laimės pojūtis. Ši korta gera kūrybininkams, reiškianti, kad sėkmė ir įkvėpimas jų neapleis ir ateityje.",
                "arcana": "minor", "suit": "cups",
                "id": 44},
            {"name": "Taurių dešimtis", "image": "Cups10.png",
                "meaning": "Visiškas pasitikėjimas, taika, harmonija, ciklo užbaigimas.",
                "r_meaning": "Pasipiktinimas, žiaurumas, liūdesys, sielvartas.",
                "description": "Jūsų vieta ten, kur jus kviečia širdis. Tai tėvynė, tėvų namai, jūsų giminės ir artimieji. Naujai sukurtai šeimai, tai gali reikšti visokeriopą sėkmę tolimesniame jaunavedžių gyvenime.",
                "arcana": "minor", "suit": "cups",
                "id": 45},
            {"name": "Taurių Valetas", "image": "Cups11.png",
                "meaning": "Jautrumas, pasitikėjimas intuicija, jausmų parodymas, kūrybingos idėjos.",
                "r_meaning": "Prisirišimas, suvedžiojimas, apgaulė, kliūtys.",
                "description": "Tai meniškos prigimties jaunas žmogus, turintis gerą širdį ir jautrią sielą. Ši korta gali reikšti ir menines paieškas, laisvalaikio užsiėmimus, hobį.",
                "arcana": "minor", "suit": "cups",
                "id": 46},
            {"name": "Taurių Riteris", "image": "Cups12.png",
                "meaning": "Romantika, nuotykis, sek savo širdimi.",
                "r_meaning": "Perdėtas emocionalumas, nerealistiškumas, nuotaikingumas.",
                "description": "Išmintingas, kūrybingas ir pastovus jaunas vyras. Su kitomis taurių kortomis jis gali reikšti nuoširdžiai mylintį jauną žmogų. Taip pat, ši korta reiškia, kad niekada neišduosite savo principų ir nepamiršite savo tikslų.",
                "arcana": "minor", "suit": "cups",
                "id": 47},
            {"name": "Taurių Dama", "image": "Cups13.png",
                "meaning": "Emocinis intelektas, intuicija, rūpestinga meilė.",
                "r_meaning": "Emocinis nestabilumas, savitarpio priklausomybė, netikrumas.",
                "description": "Švelni, atviros prigimties, bendraujanti moteris. Ji stipri asmenybė, bet rami ir pasitikinti. Korta atspindi jūsų santykius su kitais žmonėmis.",
                "arcana": "minor", "suit": "cups",
                "id": 48},
            {"name": "Taurių Karalius", "image": "Cups14.png",
                "meaning": "Emocinis brandumas, užuojauta, pusiausvyra.",
                "r_meaning": "Emocinis manipuliavimas, empatijos stoka, nuotaikingumas.",
                "description": "Pasaulietiškas, progresyvus ir kūrybingas žmogus. Jis jau yra atradęs savo vietą šiame pasaulyje, turi tvirtą motyvaciją ir tvirtą savo nuomonę. Prisiima atsakomybę ir puikiai pažįsta save.",
                "arcana": "minor", "suit": "cups",
                "id": 49},
            {"name": "Kardų tūzas", "image": "Swords01.png",
                "meaning": "Nesustojantis judėjimas, progresas, visų kliūčių įveikimas.",
                "r_meaning": "Neteisingumas, praradimas, nepelnyta valdžia, nesusipratimai ir pagieža.",
                "description": "Tūzas atneša sėkmę ir veiklos sūkurį. Nepaisant įnirtingo pasipriešinimo, pergalė, teisingumas ir pažanga yra garantuoti, nors gali tekti patobulinti savo protą, kad atlaikytumėte laukiančias dramas ir iššūkius.",
                "arcana": "minor", "suit": "swords",
                "id": 50},
            {"name": "Kardų dvejetas", "image": "Swords02.png",
                "meaning": "Balansas, paliaubos, vilties teikianti draugystė, sąjungininkas.",
                "r_meaning": "Įtarimas, nepasitikėjimas, apgaulė, išdavystė.",
                "description": "Ramybė grįžta po nesantaikos ir neramumų. Galite nepasitikėti šiomis paliaubomis, bet tai gali būti vertinga galimybė įgyti perspektyvos problemiškiems santykiams ar kitoms varginančioms asociacijoms.",
                "arcana": "minor", "suit": "swords",
                "id": 51},
            {"name": "Kardų trejetas", "image": "Swords03.png",
                "meaning": "Širdies skausmas, liūdesys, išsiskyrimas.",
                "r_meaning": "Sutrikimas, neramumai, chaosas.",
                "description": "Skausmingos, neišvengiamos situacijos sprendimas. Ši korta apima širdies skausmą, liūdesį ir gilų nusivylimą dėl santykių praradimo ar kito įsipareigojimo, kuris pakrypo į blogąją pusę.",
                "arcana": "minor", "suit": "swords",
                "id": 52},
            {"name": "Kardų ketvertas", "image": "Swords04.png",
                "meaning": "Atsigavimas, meditacija, poilsis, atsiribojimas nuo problemų.",
                "r_meaning": "Liga, sutrikimas, pašalinimas, izoliavimas. Liūdnos mintys ir depresiją.",
                "description": "Ši teigiama korta suteikia patikinimo, kad po intensyvios veiklos ir spaudimo laikotarpio galite laukti atsigavimo laikotarpis. Ketvertas simbolizuoja poilsį ir tikrą atokvėpį po konflikto ar bet kokios kitos situacijos, išeikvojusios jūsų gyvybinius išteklius.",
                "arcana": "minor", "suit": "swords",
                "id": 53},
            {"name": "Kardų penketas", "image": "Swords05.png",
                "meaning": "Pralaimėjimas, suklydimas, praradimas.",
                "r_meaning": "Užsispyręs išdidumas ir atsisakymas pasiduoti, net jei viskas prarasta.",
                "description": "Galbūt per daug stengiatės išspręsti problemą arba laimėti mūšį, kai nėra jokio kelio pasiekti sėkmę. Atėjo laikas pasitraukti, pripažinti pralaimėjimą, bei judėti toliau.",
                "arcana": "minor", "suit": "swords",
                "id": 54},
            {"name": "Kardų šešetas", "image": "Swords06.png",
                "meaning": "Atkurta ramybė, harmonija, judėjimas į priekį.",
                "r_meaning": "Delsimas, Stagnacija, išsekimas ir dėmesio trūkumas.",
                "description": "Pagaliau vyrauja harmonija, ir dabar, kai viskas tvarkoje, galite skirti laiko sau, su veržlumu grįžti prie kasdienio gyvenimo reikalavimų.",
                "arcana": "minor", "suit": "swords",
                "id": 55},
            {"name": "Kardų septynetas", "image": "Swords07.png",
                "meaning": "Nenuoširdumas, atmetimas, apgaulė ir slaptumas.",
                "r_meaning": "Nesąžiningumas, vagystė, melai ir pagieža",
                "description": "Jūs susiduriate su potencialiai pavojingu priešininku, kuris ko nors iš jūsų nori. Kadangi šiuose santykiuose nėra pasitikėjimo jausmo, norėdami laimėti mūšį, galite pasitelkti gudrumą/strategiją.",
                "arcana": "minor", "suit": "swords",
                "id": 56},
            {"name": "Kardų aštuonetas", "image": "Swords08.png",
                "meaning": "Nesėkmių ruožas, neigimas, jaustis bejėgiu, varžymas.",
                "r_meaning": "Susierzinimas, savęs kaltinimas, prarasta perspektyva.",
                "description": "Santykiai ar projektas griūna ir mažai ką norite padaryti arba jaučiate, kad galite padaryti, kad to išvengtumėte. Jūs neigiate ir dar negalite suprasti, kaip eiti į priekį arba susitaikyti su tuo, kas vyksta.",
                "arcana": "minor", "suit": "swords",
                "id": 57},
            {"name": "Kardų devynetas", "image": "Swords09.png",
                "meaning": "Baimė, nerimas, teroras, negatyvumas, gilus nelaimingas jausmas, stresas.",
                "r_meaning": "Šviesa tunelio gale, atsigavimas, tobulėjimas,  streso paleidimas.",
                "description": "Devynetas atskleidžia išsekimo laiką, kai gresia streso ir didelio nerimo galimybė. Galbūt dėl ​​to, kad esate išsekęs ir jautrus ligoms, arba dėl nuolatinių kovų.",
                "arcana": "minor", "suit": "swords",
                "id": 58},
            {"name": "Kardų dešimtis", "image": "Swords10.png",
                "meaning": "Išdavystė, pabaiga, nesėkmė, žlugimas, išsekimas.",
                "r_meaning": "Pakilimas virš problemų, neapykantų, įveikti blogiausią, išgyventi nelaimę, viskas gerėja.",
                "description": "Tai blogiausia ir geriausia korta vienu metu, kokia tik gali iškristi. Išdavystė, praradimas, pasimetimas, šaltis, meilės nebuvimas ir jau pats žemiausias įmanomas taškas. Reiktų prisiminti, kad iš žemiausio taško galima tik kilti aukštyn ir niekur kitur.",
                "arcana": "minor", "suit": "swords",
                "id": 59},
            {"name": "Kardų Valetas", "image": "Swords11.png",
                "meaning": "Uždelstos naujienos, reikia kantrybės, idėjos, įkvėpimo, planavimo, budrumo.",
                "r_meaning": "Blogos naujienos, idėjų stoka, protinio judrumo trūkumas, blaškymasis.",
                "description": "Korta atneša naujienų, kontaktų ir gandų. Tai yra tikras ženklas, kad jums prireiks išradingumo ir idėjų, kad išliktumėte priekyje. Intelektas dabar yra labai svarbus.",
                "arcana": "minor", "suit": "swords",
                "id": 60},
            {"name": "Kardų Riteris", "image": "Swords12.png",
                "meaning": "Ambicingumas, dideli pokyčiai, galimybės, išnaudokite akimirką, mąstantis.",
                "r_meaning": "Praleistos galimybės, netaktiškas, įžeidžiantis, nenuoširdus, ryžtingas, priekabus.",
                "description": "Kardų Riteris praneša apie būsimą mūšį, kuriame privalote kovoti, kad būtų rastas problemos sprendimas. Korta sako, kad jūs turite atrasti pakankamai energijos ir ryžto drąsiai priimti iššūkį.",
                "arcana": "minor", "suit": "swords",
                "id": 61},
            {"name": "Kardų Dama", "image": "Swords13.png",
                "meaning": "Sąžiningas, teisingas, nuoširdus, nepriklausomas, komunikabilus, šmaikštus.",
                "r_meaning": "Pernelyg kritiškas, pesimistiškas, empatijos stoka, grubus.",
                "description": "Ši korta rodo, kad Jums užteks intelekto, iškalbos ir lojalumo... iki tam tikro taško. Kaip situacijos simbolis korta rodo trumpalaikę pagalbą; Jums gali patikti draugo ar kolegos parama, kai siekiate panašių tikslų ar gyvenimo būdo.",
                "arcana": "minor", "suit": "swords",
                "id": 62},
            {"name": "Kardų Karalius", "image": "Swords14.png",
                "meaning": "Struktūra, rutina, protingas, racionalus, logiškas, jėga, manieros.",
                "r_meaning": "Netinkamai naudojamas intelektas, rutinos trūkumas, neracionalus, nelogiškas, pamišęs dėl valdžios, diktatorius.",
                "description": "Pasitelkite savo talentą spręsti problemas, lyderystę būti vadovu ir pamatyti didesnį vaizdą. Neapsiimkite visko daryti patys, kitiems palikite spręsti smulkesnius klausimus. Kaip situacijos simbolis, projektai įsibėgėja, tačiau atkreipkite dėmesį į detales, kad išvengtumėte vėlavimo.",
                "arcana": "minor", "suit": "swords",
                "id": 63},
            {"name": "Monetų Tūzas", "image": "Pentacles01.png",
                "meaning": "Naujos finansinės galimybės, naujas darbas/verslas, pinigai, klestėjimas, saugumas.",
                "r_meaning": "Pinigų trūkumas, prasta finansų kontrolė, galimybių stoka arba prarastos galimybės.",
                "description": "Ši korta rodo finansinį pelną didėjančių investicijų ar netikėtų dovanų, nuo premijų iki honorarų gavimo ar konkurso laimėjimo. Tūzas išreiškia visišką materialinį saugumą ir suteikia pasitikėjimo po neapibrėžtumo laikotarpio. Korta taip pat signalizuoja apie sėkmę verslo pradžiai ir naujiems santykiams.",
                "arcana": "minor", "suit": "pentacles",
                "id": 64},
            {"name": "Monetų dvejetas", "image": "Pentacles02.png",
                "meaning": "Pusiausvyra, bandymas ją rasti, išradingumas, pakilimai ir nuosmukiai, prisitaikymas, lankstumas.",
                "r_meaning": "Pusiausvyros trūkumas, organizuotumo stoka, prasti finansiniai sprendimai, pervargimas.",
                "description": "Jūsų finansinė padėtis gali būti nepastovi, bet su atidžiu pinigų valdymu jų užteks esamam laikotarpiui. Gyvenimas nenuspėjamas, verslas ar partnerystės vyksta sklandžiai.",
                "arcana": "minor", "suit": "pentacles",
                "id": 65},
            {"name": "Monetų trejetas", "image": "Pentacles03.png",
                "meaning": "Studijos, augimas, sunkus darbas, įsipareigojimas, sėkmės pagrindas.",
                "r_meaning": "Nesimokymas iš klaidų, nenoras mokytis, augimo stoka, prasta darbo etika.",
                "description": "Tai korta, kuri reiškia sėkmės prognozę. Jei sunkiai dirbote kurdami smulkųjį verslą nuo nulio arba atradote naują kūrybinį kelią, mėgausitės didžiuliu pasididžiavimu ir pasiekimais.",
                "arcana": "minor", "suit": "pentacles",
                "id": 66},
            {"name": "Monetų ketvertas", "image": "Pentacles04.png",
                "meaning": "Atsikratyti seno, paleisti žmones, turtą ar problemas, dosnumas, dalijimasis, davimas kitiems",
                "r_meaning": "Žmonių/turtų/problemų laikymasis, praeities problemos, kaupimas, šykštumas.",
                "description": "Tai, dėl ko dirbote, pagaliau užtikrinta. Ketvertas rodo stabilumą ir tvirtus pagrindus ateičiai, todėl dabar turite tvirtą pagrindą, ant kurio galite kurti savo imperiją.",
                "arcana": "minor", "suit": "pentacles",
                "id": 67},
            {"name": "Monetų penketas", "image": "Pentacles05.png",
                "meaning": "Laikini finansiniai sunkumai, neigiami aplinkybių pasikeitimai.",
                "r_meaning": "Finansų pagerėjimas / sėkmė, sunkumų pabaiga, teigiami pokyčiai.",
                "description": "Penketas rodo skolą, skurdą ir sunkumus, tačiau ši korta dažnai atskleidžia didėjančios skolos baimę, o ne tikrą praradimą. Galima izoliacija nuo grupės veiklos, galbūt dėl mažų lėšų. Gausite antrą galimybę ištaisyti visas finansines klaidas, sutaupydami banko likutį ir, galbūt, santykius.",
                "arcana": "minor", "suit": "pentacles",
                "id": 68},
            {"name": "Monetų šešetas", "image": "Pentacles06.png",
                "meaning": "Gausite dovana, ji gali atvykti užsimaskavus kaip finansinė investicija į jūsų verslą, mažas giminaičio palikimas, konkurso laimėjimas, premija ar kita visiškai netikėta išmoka. ",
                "r_meaning": "Dovanos, dosnumas, labdara, aukos, pinigai, bendruomenė, pagalba, parama.",
                "description": "Dosnumo trūkumas/piktnaudžiavimas, piktnaudžiavimas valdžia ar padėtimi.",
                "arcana": "minor", "suit": "pentacles",
                "id": 69},
            {"name": "Monetų septynetas", "image": "Pentacles07.png",
                "meaning": "Sunkus darbas atsiperka, derlius, atlygis, pelnas, rezultatai, išmokos.",
                "r_meaning": "Blogas verslas/finansų valdymas, nebaigimas to, ką pradėjote, tingumas.",
                "description": "Korta rodo, kad turite didelį potencialą pasiekti savo tikslus. Nuo paaukštinimo iki naujų įgūdžių įgijimo – turite viską, ko reikia sėkmei. Tačiau tai tik pradžia, todėl būkite ryžtingi. Nenukrypkite nuo pasirinkto kelio.",
                "arcana": "minor", "suit": "pentacles",
                "id": 70},
            {"name": "Monetų aštuonetas", "image": "Pentacles08.png",
                "meaning": "Naujas darbas, savarankiška veikla, verslo kūrimas, prekyba, reputacija.",
                "r_meaning": "Pasikartojantis/nuobodus darbas, nesėkmė, prasta kokybė, skubotas darbas, bloga reputacija.",
                "description": "Galite sulaukti pasiūlymo, atnešančio materialinį atlygį. Aštuonetas atskleidžia, kad jausitės vertinami dėl šios galimybės, todėl patartina priimti kvietimą, nes jis suteiks jums tai, ko reikia – nuo tolesnio mokymosi iki nedidelio projekto, kuris jums patiks.",
                "arcana": "minor", "suit": "pentacles",
                "id": 71},
            {"name": "Monetų devynetas", "image": "Pentacles09.png",
                "meaning": "Nepriklausomybė, sėkmė, finansinis stabilumas/saugumas, pelnas, klestėjimas.",
                "r_meaning": "Nepriklausomybės/stabilumo/saugumo stoka, neapgalvotos išlaidos, per sunkus darbas.",
                "description": "Harmonijos korta – baigiasi ginčai dėl triukšmo su kaimynais, statybos darbai ar kivirčai šeimoje. Tvarka atkurta, pinigai teka, dabar galite mėgautis finansiniu saugumu, dėl kurio dirbote. ",
                "arcana": "minor", "suit": "pentacles",
                "id": 72},
            {"name": "Monetų dešimtis", "image": "Pentacles10.png",
                "meaning": "Vienkartinė išmoka, testamentas, aktai, palikimas.",
                "r_meaning": "Ginčijamas palikimas, netikėti pokyčiai, finansinė nelaimė.",
                "description": "Dešimtukas dažnai yra atsitiktinė korta šeimoms, palanki esamoms ir būsimoms kartoms, todėl gali nuspėti laimingą santuoką ir vaikus. Pinigine išraiška Dešimtukas, kaip didžiausia monetų korta, atskleidžia per kartų kartas sukauptą turtą, todėl gali būti naudingi akcijų dividendai, paveldėjimas arba dosnaus giminaičio ar draugo dovana.",
                "arcana": "minor", "suit": "pentacles",
                "id": 73},
            {"name": "Monetų Valetas", "image": "Pentacles11.png",
                "meaning": "Tikslų kėlimas, plano kūrimas, pamatų klojimas, galimybių išnaudojimas.",
                "r_meaning": "Tikslų neturėjimas, sveiko proto stoka, neatsakingas, tinginys.",
                "description": "Korta primenanti, kad reikia būti atsakingam ir darbščiam; simbolizuoja sunkų darbą ir pataria nuolat tvarkyti piniginius reikalus, kad išvengtumėte trūkumo ateityje.",
                "arcana": "minor", "suit": "pentacles",
                "id": 74},
            {"name": "Monetų Riteris", "image": "Pentacles12.png",
                "meaning": "Kantrus, praktiškas, ištikimas, atsakingas, atkaklus, saugus.",
                "r_meaning": "Nekantrus, tingus, apatija, sveiko proto stoka, nestabilus.",
                "description": "Reikia suteikti energijos ir tikslo verslo reikalams, vykdomiems projektams ir asmeniniams piniginiams reikalams. Nors ir nėra įkvėpimo ar kūrybiškumo – turite tvirtą poziciją. ",
                "arcana": "minor", "suit": "pentacles",
                "id": 75},
            {"name": "Monetų Dama", "image": "Pentacles13.pg",
                "meaning": "Klestėjimas, sėkmė, turtas, prabanga.",
                "r_meaning": "Nepagrįstas, ambicingas, turintis vilčių, lėkštas.",
                "description": "Korta atnešanti stabilumo, dovanų reiškia apsaugą kuri numato/apsaugo laimę materialiai ir emociškai. ",
                "arcana": "minor", "suit": "pentacles",
                "id": 76},
            {"name": "Monetų Karalius", "image": "Pentacles14.png",
                "meaning": "Subrendęs vyras, sėkmingas, turtingas verslininkas, tobulėjantis.",
                "r_meaning": "Nesėkmingas verslininkas, korupcija, nestabilumas, prastas sprendimas.",
                "description": "Natūralus problemų sprendimas, simbolizuoja praktiškumą, saugumą ir pasitenkinimą. Dažnai yra susiję su nuosavybe; Kalbant apie asmenines savybes, jis yra žmogus, kuriuo galite pasikliauti darydami tai, ką žada. Korta taip pat yra geras ženklas darbui ir verslui, nes ji rodo stabilumą ir ilgalaikį finansinį saugumą. ",
                "arcana": "minor", "suit": "pentacles",
                "id": 77}
        ]
        Card.objects.bulk_create([Card(**data) for data in cards_list])
        self.stdout.write(self.style.SUCCESS('Successfully bulk created cards'))
        