# Generated by Django 4.1.7 on 2023-03-28 18:20

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cards', models.CharField(help_text='Trumpa informacija apie kortas, ištrauktas būrimo metu', max_length=500, verbose_name='Kortos')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Data')),
            ],
        ),
    ]
