# Generated by Django 4.1.7 on 2023-04-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0007_readingcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='/profile_pictures/default.jpg', upload_to='profile_pictures'),
        ),
    ]
