# Generated by Django 4.1.7 on 2023-04-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0012_alter_card_arcana_alter_card_suit_delete_arcana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Nuotrauka'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(help_text='Išsamus simbolizmo ir reikšmės aprašymas', max_length=5000, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.CharField(choices=[('none', ''), ('wands', 'Lazdos'), ('cups', 'Taurės'), ('swords', 'Kardai'), ('pentacles', 'Monetos')], help_text='Pasirinkite rūšį', max_length=9, null=True, verbose_name='Rūšis'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
    ]
