# Generated by Django 4.1.7 on 2023-04-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0013_card_image_alter_card_description_alter_card_suit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['id']},
        ),
    ]
