# Generated by Django 4.1.7 on 2023-04-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0014_alter_card_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Sukurta'),
        ),
    ]
