# Generated by Django 4.1.7 on 2023-04-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0017_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
