# Generated by Django 4.2 on 2023-04-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0018_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_pictures/peter.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
